### ISSUE TITLE
[Bug]: discord.ext.commands.errors.CheckFailure: The global check functions for command help failed.

### ISSUE THREAD

**Issue by tuna2134** [RextTeam/rt-bot#153]
### What happened?

しらね

### Version

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4367+g64849ebc
- aiohttp v3.8.1
- system info: Linux 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022

### Relevant log output

```shell
Jun 24 13:39:47 mc-fdc.f5.si python[661]: [RT.Bot] Traceback (most recent call last):
Jun 24 13:39:47 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
Jun 24 13:39:47 mc-fdc.f5.si python[661]:     await ctx.command.invoke(ctx)
Jun 24 13:39:47 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1595, in invoke
Jun 24 13:39:47 mc-fdc.f5.si python[661]:     await self.prepare(ctx)
Jun 24 13:39:47 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 891, in prepare
Jun 24 13:39:47 mc-fdc.f5.si python[661]:     if not await self.can_run(ctx):
Jun 24 13:39:47 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1237, in can_run
Jun 24 13:39:47 mc-fdc.f5.si python[661]:     raise CheckFailure(f'The global check functions for command {self.qualified_name} failed.')
Jun 24 13:39:47 mc-fdc.f5.si python[661]: discord.ext.commands.errors.CheckFailure: The global check functions for command afk failed.
Jun 24 20:55:17 mc-fdc.f5.si python[661]: [RT.Bot] Traceback (most recent call last):
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     await ctx.command.invoke(ctx)
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 987, in invoke
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     await self.prepare(ctx)
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 891, in prepare
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     if not await self.can_run(ctx):
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1237, in can_run
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     raise CheckFailure(f'The global check functions for command {self.qualified_name} failed.')
Jun 24 20:55:17 mc-fdc.f5.si python[661]: discord.ext.commands.errors.CheckFailure: The global check functions for command help failed.
Jun 24 20:55:17 mc-fdc.f5.si python[661]: [RT.Bot] Traceback (most recent call last):
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     await ctx.command.invoke(ctx)
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 987, in invoke
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     await self.prepare(ctx)
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 891, in prepare
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     if not await self.can_run(ctx):
Jun 24 20:55:17 mc-fdc.f5.si python[661]:   File "/home/rocky/rt/rt-bot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1237, in can_run
Jun 24 20:55:17 mc-fdc.f5.si python[661]:     raise CheckFailure(f'The global check functions for command {self.qualified_name} failed.')
Jun 24 20:55:17 mc-fdc.f5.si python[661]: discord.ext.commands.errors.CheckFailure: The global check functions for command help failed.
```

**Comment by tasuren** [comment]
グローバルチェックに何か問題があるようだ。

**Comment by yaakiyu** [comment]
DMで実行しようとしたとか？

**Comment by tuna2134** [comment]
しらね
DMの可能性もあるけどね

**Comment by tuna2134** [comment]
このエラー表示を変えてほしい

**Comment by tasuren** [comment]
> このエラー表示を変えてほしい

Yeah

**Comment by tasuren** [comment]
修正した。
